#################################################################
# Dockerfile
#
# Version:          dev
# Software:         HS Rats Genotyping Pipeline Step 1
# Software Version: dev
# about.summary:    HS Rats Genotyping Pipeline Step 1
# about.tags:       Genomics
# BASE IMAGE :      alpine:latest
#################################################################
# Base image
FROM alpine:latest